sudo: false

language: php

language: php

php:
- 5.5
- 5.6
- 7.0

cache:
  directories:
  - .Build/vendor
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini

install:
- composer install

script:
  # Run PHP lint on all PHP files.
  - find Classes/ Tests/ -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
